version: "3"

services:

  webserver:
    build: '.docker/webserver/'
    ports:
      - 80:80
    volumes:
      - ./web:/var/www/html

  database:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - data:/var/lib/mysql

  adminer:
    image: adminer:latest
    ports:
      - 8080:8080

volumes:
  data:
